export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "GET_ERRORS";
export const IS_LOADING = "IS_LOADING";

export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const FETCH_WORKOUTS = "FETCH_WORKOUTS";
export const FETCH_WORKOUT = "FETCH_WORKOUT";

export const FETCH_EXERCISE = "FETCH_EXERCISE";
export const FETCH_EXERCISES = "FETCH_EXERCISES";
export const DELETE_EXERCISE = "DELETE_EXERCISE";

export const FETCH_SET = "FETCH_SET";
