export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "GET_ERRORS";
export const IS_LOADING = "IS_LOADING";

export const ADD_WORKOUT = "ADD_WORKOUT";
export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const EDIT_WORKOUT = "EDIT_WORKOUT";
export const FETCH_WORKOUTS = "FETCH_WORKOUTS";
export const FETCH_WORKOUT = "FETCH_WORKOUT";
